"""
utils/slides_generator.py
==========================
Generates a PowerPoint presentation from MeetingInsights.
Uses Unsplash API to fetch relevant images for each slide.
"""

import os
import io
import requests
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN
from src.core.analyser import MeetingInsights

# ── Colours ───────────────────────────────────────────────────────────────────
NAVY       = RGBColor(0x0A, 0x0F, 0x1E)
CYAN       = RGBColor(0x00, 0xE5, 0xFF)
CYAN_DARK  = RGBColor(0x00, 0x90, 0xA8)
WHITE      = RGBColor(0xFF, 0xFF, 0xFF)
LIGHT_GREY = RGBColor(0xCB, 0xD5, 0xE1)


def _fetch_image(query: str) -> bytes | None:
    """Fetch a relevant photo from Unsplash by keyword."""
    key = os.environ.get("UNSPLASH_ACCESS_KEY")
    if not key:
        return None
    try:
        r = requests.get(
            "https://api.unsplash.com/search/photos",
            params={"query": query, "per_page": 1, "orientation": "landscape"},
            headers={"Authorization": f"Client-ID {key}"},
            timeout=10,
        )
        url = r.json()["results"][0]["urls"]["regular"]
        img_r = requests.get(url, timeout=15)
        return img_r.content
    except Exception as exc:
        print(f"Image fetch failed: {exc}")
        return None


def _set_background(slide) -> None:
    fill = slide.background.fill
    fill.solid()
    fill.fore_color.rgb = NAVY


def _add_text(slide, text, left, top, width, height,
              size, bold=False, color=WHITE, align=PP_ALIGN.LEFT) -> None:
    txBox = slide.shapes.add_textbox(left, top, width, height)
    tf = txBox.text_frame
    tf.word_wrap = True
    p = tf.paragraphs[0]
    p.alignment = align
    run = p.add_run()
    run.text = text
    run.font.size = Pt(size)
    run.font.bold = bold
    run.font.color.rgb = color


def _build_cover(prs, insights) -> None:
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    _set_background(slide)

    img_bytes = _fetch_image(insights.title)
    if img_bytes:
        pic = slide.shapes.add_picture(
            io.BytesIO(img_bytes),
            Inches(0), Inches(0), prs.slide_width, prs.slide_height
        )
        # Send image to back
        slide.shapes._spTree.remove(pic._element)
        slide.shapes._spTree.insert(2, pic._element)

        # Dark overlay
        rect = slide.shapes.add_shape(1, Inches(0), Inches(0), prs.slide_width, prs.slide_height)
        rect.fill.solid()
        rect.fill.fore_color.rgb = NAVY
        rect.line.fill.background()

    type_colors = {
        "Meeting": "00E5FF", "Class": "A78BFA",
        "Webinar": "34D399", "Presentation": "F59E0B"
    }
    color_hex = type_colors.get(insights.content_type, "00E5FF")
    r, g, b = int(color_hex[:2], 16), int(color_hex[2:4], 16), int(color_hex[4:], 16)

    _add_text(slide, f"[ {insights.content_type.upper()} ]",
              Inches(0.5), Inches(1.5), Inches(9), Inches(0.5),
              12, bold=True, color=RGBColor(r, g, b), align=PP_ALIGN.CENTER)

    _add_text(slide, insights.title,
              Inches(0.5), Inches(2.2), Inches(9), Inches(2.0),
              36, bold=True, color=WHITE, align=PP_ALIGN.CENTER)

    _add_text(slide, f"Tone: {insights.sentiment}",
              Inches(0.5), Inches(4.4), Inches(9), Inches(0.5),
              14, color=LIGHT_GREY, align=PP_ALIGN.CENTER)

    _add_text(slide, "Generated by MeetingMind AI  ·  Whisper + Claude + Unsplash",
              Inches(0.5), Inches(6.8), Inches(9), Inches(0.4),
              9, color=CYAN_DARK, align=PP_ALIGN.CENTER)


def _build_summary(prs, insights) -> None:
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    _set_background(slide)

    _add_text(slide, "RESUMO EXECUTIVO",
              Inches(0.5), Inches(0.3), Inches(9), Inches(0.5),
              11, bold=True, color=CYAN)

    _add_text(slide, insights.title,
              Inches(0.5), Inches(0.9), Inches(9), Inches(0.7),
              24, bold=True, color=WHITE)

    _add_text(slide, insights.summary,
              Inches(0.5), Inches(1.8), Inches(8.8), Inches(5.0),
              13, color=LIGHT_GREY)


def _build_keypoint(prs, point, index, total) -> None:
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    _set_background(slide)

    img_bytes = _fetch_image(point[:60])
    if img_bytes:
        slide.shapes.add_picture(
            io.BytesIO(img_bytes),
            Inches(5.2), Inches(1.0), Inches(4.6), Inches(5.8)
        )

    _add_text(slide, f"PONTO-CHAVE  {index:02d} / {total:02d}",
              Inches(0.5), Inches(0.3), Inches(4.5), Inches(0.4),
              10, bold=True, color=CYAN)

    _add_text(slide, point,
              Inches(0.5), Inches(1.0), Inches(4.5), Inches(5.8),
              13, color=LIGHT_GREY)


def _build_concept(prs, concept, index) -> None:
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    _set_background(slide)

    img_bytes = _fetch_image(concept.concept)
    if img_bytes:
        slide.shapes.add_picture(
            io.BytesIO(img_bytes),
            Inches(5.2), Inches(1.0), Inches(4.6), Inches(5.8)
        )

    _add_text(slide, f"CONCEITO  {index:02d}",
              Inches(0.5), Inches(0.3), Inches(4.5), Inches(0.4),
              10, bold=True, color=CYAN)

    _add_text(slide, concept.concept,
              Inches(0.5), Inches(0.9), Inches(4.5), Inches(0.9),
              26, bold=True, color=WHITE)

    _add_text(slide, concept.explanation,
              Inches(0.5), Inches(2.0), Inches(4.5), Inches(4.8),
              13, color=LIGHT_GREY)


def _build_example(prs, example, index) -> None:
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    _set_background(slide)

    img_bytes = _fetch_image(example.context)
    if img_bytes:
        slide.shapes.add_picture(
            io.BytesIO(img_bytes),
            Inches(5.2), Inches(1.0), Inches(4.6), Inches(5.8)
        )

    _add_text(slide, f"EXEMPLO  {index:02d}",
              Inches(0.5), Inches(0.3), Inches(4.5), Inches(0.4),
              10, bold=True, color=CYAN)

    _add_text(slide, example.context,
              Inches(0.5), Inches(0.9), Inches(4.5), Inches(0.8),
              20, bold=True, color=WHITE)

    _add_text(slide, example.description,
              Inches(0.5), Inches(1.9), Inches(4.5), Inches(4.8),
              13, color=LIGHT_GREY)


def _build_action_items(prs, insights) -> None:
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    _set_background(slide)

    _add_text(slide, "ACTION ITEMS",
              Inches(0.5), Inches(0.3), Inches(9), Inches(0.5),
              11, bold=True, color=CYAN)

    top = Inches(1.1)
    for item in insights.action_items[:6]:
        _add_text(slide, f"▸  {item.task}",
                  Inches(0.5), top, Inches(7), Inches(0.6),
                  13, color=WHITE)
        _add_text(slide, f"{item.owner}  ·  {item.deadline}",
                  Inches(7.5), top, Inches(2), Inches(0.6),
                  10, color=CYAN)
        top += Inches(0.85)


def generate_slides(insights: MeetingInsights) -> bytes:
    """
    Generate a PowerPoint from MeetingInsights with Unsplash images.

    Args:
        insights: Structured insights from analyse_transcript().

    Returns:
        PPTX file as bytes for st.download_button().
    """
    prs = Presentation()
    prs.slide_width = Inches(10)
    prs.slide_height = Inches(7.5)

    _build_cover(prs, insights)
    _build_summary(prs, insights)

    if insights.content_type == "Meeting":
        _build_action_items(prs, insights)
        for i, decision in enumerate(insights.key_decisions, 1):
            _build_keypoint(prs, decision, i, len(insights.key_decisions))
    else:
        for i, point in enumerate(insights.key_points, 1):
            _build_keypoint(prs, point, i, len(insights.key_points))
        for i, concept in enumerate(insights.key_concepts, 1):
            _build_concept(prs, concept, i)
        for i, example in enumerate(insights.examples, 1):
            _build_example(prs, example, i)

    buf = io.BytesIO()
    prs.save(buf)
    return buf.getvalue()